# Generated by Django 3.1.2 on 2020-10-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField()),
                ('document_number', models.IntegerField()),
                ('type_of_invoice', models.CharField(max_length=100)),
                ('net_due_date', models.DateField()),
                ('doc_date', models.DateField()),
                ('pstng_date', models.DateField()),
                ('amount', models.IntegerField()),
                ('vendor_code', models.CharField(max_length=100)),
                ('vendor_name', models.TextField()),
                ('vendor_type', models.CharField(max_length=100)),
            ],
        ),
    ]
